name: flutter_privacy_screen
description: A flutter plugin that blurs / blacks the screen in the task manager.
version: 0.0.1
author: Jeroen Trappers <jeroen.trappers@gmail.com>
homepage: https://github.com/jeroentrappers/flutter_privacy_screen 

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: be.appmire.flutter_privacy_screen
    pluginClass: FlutterPrivacyScreenPlugin
